const PDFDocument = require("pdfkit");

const generateInvoicePDF = async ({
  payment,
  therapist,
  client,
  packageData,
}) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      const chunks = [];

      doc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      doc.on("end", () => {
        resolve(Buffer.concat(chunks));
      });

      doc.on("error", reject);

      const invoiceNumber = `UNF-${payment._id
        .toString()
        .slice(-8)
        .toUpperCase()}`;

      const invoiceDate = new Date(
        payment.updatedAt || payment.createdAt || Date.now()
      );

      const amount = Number(payment.amount || 0);

      // Header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("UNFAZED", { align: "center" });

      doc
        .fontSize(10)
        .font("Helvetica")
        .text("Therapist Practice Management Platform", {
          align: "center",
        });

      doc.moveDown(2);

      doc
        .fontSize(18)
        .font("Helvetica-Bold")
        .text("TAX INVOICE", { align: "center" });

      doc.moveDown(1.5);

      // Invoice information
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Invoice Number: ${invoiceNumber}`)
        .text(`Invoice Date: ${invoiceDate.toLocaleDateString("en-IN")}`)
        .text(`Payment Status: ${payment.status.toUpperCase()}`);

      doc.moveDown(1.5);

      // Therapist
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Therapist");

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(therapist?.name || "Unfazed Therapist")
        .text(therapist?.email || "");

      doc.moveDown(1);

      // Client
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Bill To");

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(client?.name || "Client")
        .text(client?.email || "")
        .text(client?.phone || "");

      doc.moveDown(2);

      // Package details
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text("Purchase Details");

      doc.moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Package: ${packageData?.name || "Therapy Package"}`)
        .text(
          `Sessions: ${packageData?.sessionCount || 1}`
        )
        .text(
          `Validity: ${packageData?.validityDays || "-"} days`
        );

      doc.moveDown(1.5);

      // Amount table
      doc
        .fontSize(11)
        .font("Helvetica-Bold")
        .text("Amount Details");

      doc.moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Package Amount: INR ${amount.toFixed(2)}`)
        .text(
          `Platform Fee: INR ${Number(
            payment.platform_fee || 0
          ).toFixed(2)}`
        )
        .text(
          `Net Amount: INR ${Number(
            payment.net_amount || amount
          ).toFixed(2)}`
        );

      doc.moveDown(1);

      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text(
          `Total Paid: INR ${amount.toFixed(2)}`
        );

      doc.moveDown(2);

      doc
        .fontSize(9)
        .font("Helvetica")
        .text(
          "GST-style invoice generated by Unfazed for demonstration/testing purposes."
        );

      doc.moveDown(0.5);

      doc.text(
        "Payment Gateway: Razorpay (Test Mode)"
      );

      if (payment.gateway_transaction_id) {
        doc.text(
          `Transaction ID: ${payment.gateway_transaction_id}`
        );
      }

      doc.moveDown(2);

      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(
          "Thank you for using Unfazed.",
          { align: "center" }
        );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateInvoicePDF,
};